import React, { useRef, useEffect, useContext } from 'react';
import * as d3 from 'd3';
import scatterplot from './Chart/scatterplot';
import sizeLegend from './Chart/sizeLegend';
import colorLegend from './Chart/colorLegend';
import ToolTipContext from '../../../context/ToolTipContext';
import { debounce } from '../SharedD3Exports/utils';
import { dataFieldsByColumn } from '../../../utils/constants';
import './Scatterplot.scss';

const DEBOUNCE_DELAY = 50;
const margin = { top: 120, right: 35, bottom: 75, left: 80 };

const scaleConstants = {
  Lifestage: ['X', 'Y', 'B', 'M', 'S'],
  Prime: ['Younger', 'Mid', 'Mature'],
  NewLifestage: ['Y', 'C', 'E', 'M'],
};

const generateColorScale = (inputArray) => {
  // pallette autogenerated from cvent colors was ugly, so I used:
  // https://digitalsynopsis.com/wp-content/uploads/2017/08/beautiful-color-schemes-combinations-palettes-12.png
  switch (inputArray.length) {
    case 5:
      return d3
        .scaleOrdinal()
        .domain(inputArray)
        .range(['#e8f1f2', '#1b98e0', '#247ba0', '#006494', '#13293d']);
    case 4:
      return d3
        .scaleOrdinal()
        .domain(inputArray)
        .range(['#e8f1f2', '#1b98e0', '#247ba0', '#13293d']);
    case 3:
      return d3
        .scaleOrdinal()
        .domain(inputArray)
        .range(['#e8f1f2', '#247ba0', '#13293d']);
    default:
      return d3
        .scaleOrdinal()
        .domain(inputArray)
        .range(
          d3.range(inputArray.length - 1).map(
            d3
              .scaleLinear()
              .domain([0, inputArray.length - 1])
              .range(['#13293d', '#e8f1f2'])
          )
        );
  }
};

export const Scatterplot = ({ data, chartTitle, chartSubtitle }) => {
  const chartDivRef = useRef(null);
  const scatterplotRef = useRef(null);
  const sizeLegendRef = useRef(null);
  const colorLegendRef = useRef(null);
  const toolTipRef = useContext(ToolTipContext);
  const hideTooltip = () => toolTipRef.current.hideToolTip();

  const drawScatterplot = () => {
    if (!chartDivRef.current) return;

    chartDivRef.current.innerHTML = '';
    const topCircleRadius = 10;
    const { width, height } = d3
      .select(chartDivRef.current)
      .node()
      .getBoundingClientRect();
    const xValue = (d) => d[dataFieldsByColumn['referencePercentage']];
    const yValue = (d) => d[dataFieldsByColumn['index']];
    const rValue = (d) => d[dataFieldsByColumn['targetPercentage']];

    const svg = d3
      .select(chartDivRef.current)
      .append('svg')
      .attr('preserveAspectRatio', 'xMinYMin meet')
      .attr('viewBox', `0 0 ${width} ${height}`);
    scatterplotRef.current = svg.append('g').attr('class', 'scatterplot');
    sizeLegendRef.current = svg.append('g').attr('class', 'sizeLegend');
    colorLegendRef.current = svg.append('g').attr('class', 'colorLegend');

    const radiusScale = d3
      .scaleSqrt()
      .domain(d3.extent(data, rValue))
      .range([1.5, topCircleRadius]);

    const colorScale = generateColorScale(
      scaleConstants[data[0][dataFieldsByColumn.subPage]]
    );

    sizeLegendRef.current
      .attr('transform', `translate(${margin.left + 60},${margin.top - 110})`)
      .call(sizeLegend, {
        radiusScale,
        spacing: 80,
        textOffset: 8,
        numTicks: 5,
        circleFill: 'lightblue',
      })
      .append('text')
      .text('% of total')
      .attr('class', 'legend-text fill-gray')
      .attr('transform', `translate(-75,5)`);

    colorLegendRef.current
      .attr('transform', `translate(${margin.left + 60},${margin.top - 80})`)
      .call(colorLegend, {
        colorScale,
        spacing: 20,
      })
      .append('text')
      .text('group')
      .attr('class', 'legend-text fill-gray')
      .attr('transform', `translate(-60,5)`);

    scatterplotRef.current.call(scatterplot, {
      data,
      width,
      height,
      margin,
      radiusScale,
      colorScale,
      xValue,
      yValue,
      rValue,
      toolTipRef,
    });

    svg.on(
      'mouseleave',
      debounce(() => {
        hideTooltip();
      }, DEBOUNCE_DELAY)
    );
  };

  useEffect(() => {
    drawScatterplot();
  }, [data]);

  useEffect(() => {
    window.addEventListener('resize', drawScatterplot, false);
  }, []);

  return (
    <div
      style={{
        width: '100%',
        height: '100%',
        display: 'flex',
        flexDirection: 'column',
      }}
    >
      <h3
        className="viz-title text-primary"
        style={{ marginLeft: '25px', marginBottom: '-5px' }}
      >
        {chartTitle}
      </h3>
      <p
        className="viz-subtitle text-primary"
        style={{ marginLeft: '25px', marginTop: '0px' }}
      >
        {chartSubtitle}
      </p>
      <div style={{ width: '100%', flexGrow: 1 }} ref={chartDivRef} />
    </div>
  );
};
